apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "valhalla-incidents.fullname" . }}
  labels:
    {{- include "valhalla-incidents.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "valhalla-incidents.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "valhalla-incidents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valhalla-incidents.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: incidents-vol
          persistentVolumeClaim:
            claimName: {{ .Values.volname }}-pvc
        - name: workdir
          emptyDir: {}
      {{- end }}
      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: incidents-vol
              mountPath: "/mnt"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.env }}
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            - name: volume_prefix
              value: {{ .Values.volume_prefix }}
