{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volname }}
spec:
  storageClassName: valhalla-client
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
  - {{ .Values.persistence.accessMode }}
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
{{- end }}
