{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volname }}-pvc
spec:
  storageClassName: valhalla-tomtom-client
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- end }}