apiVersion: v1
kind: Service
metadata:
  name: statefull
  labels:
    {{- include "valhalla-incidents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "valhalla-incidents.selectorLabels" . | nindent 4 }}