apiVersion: v1
kind: Service
metadata:
  name: stateful
  labels:
    {{- include "valhalla-incidents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "valhalla-incidents.selectorLabels" . | nindent 4 }}