apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
    {{- include "valhalla-incidents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
  selector:
    {{- include "valhalla-incidents.selectorLabels" . | nindent 4 }}