apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
    {{- include "incidents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8002
      protocol: TCP
  selector:
    {{- include "incidents.selectorLabels" . | nindent 4 }}
